### ISSUE TITLE
TypeError on empty string

### ISSUE THREAD

**Issue by michaelmior** [k4m4/lexis#1]
I get the error below when trying lexis with an empty string

```
$ echo '' | lexis
TypeError: Cannot read property 'length' of null
    at module.exports (/home/mmior/.dotfiles/node/node_modules/lexis-count/index.js:9:46)
    at getStdin.then.stdin (/home/mmior/.dotfiles/node/node_modules/lexis-cli/cli.js:28:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
``

**Comment by k4m4** [comment]
Should be fixed in [990e176](https://github.com/k4m4/lexis-cli/commit/990e1764543ccb9b9728d1ce0d0eff63d65b6630). Thanks!
